repos:
-   repo: https://github.com/psf/black
    rev: '19.10b0'
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.770'
    hooks:
    -   id: mypy
-   repo: https://github.com/Yelp/detect-secrets
    rev: 'v0.13.0'
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
-   repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'
    hooks:
    - id: bandit
      args: ['--exclude', 'tests/*,.venv']
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: cookiecutter_pypackage/
